FROM python:3.11-slim-bookworm as base

RUN apt-get update && apt-get install -y --no-install-recommends \
    # install calibre system dependencies
    xdg-utils \
    xz-utils \
    libopengl0 \
    libegl1 \
    libxcb-cursor0 \
    libfreetype6 \
    libfontconfig1 \
    libnss3 \
    libxcomposite1 \
    libxdamage1 \
    libxrandr2 \
    libxtst6 \
    libxkbcommon0 \
    libxcb-icccm4 \
    libxcb-image0 \
    libxcb-keysyms1 \
    libxcb-randr0 \
    libxcb-render-util0 \
    libxcb-xinerama0 \
    libxcb-xkb1 \
    libxkbcommon-x11-0 && \
    apt-get remove --purge --auto-remove -y && \
    apt-get clean && \
    rm -rf \
    /tmp/* \
    /var/lib/apt/lists/* \
    /var/tmp/*

ENV CALIBRE_CONFIG_DIRECTORY=/app/.calibre \
    CALIBRE_TEMP_DIR=/tmp \
    CALIBRE_CACHE_DIRECTORY=/tmp

RUN useradd -s /bin/bash calibre -u 1000 && \
    mkdir -p ${CALIBRE_CONFIG_DIRECTORY} && \
    chown -R 1000:1000 ${CALIBRE_CONFIG_DIRECTORY}

EXPOSE 8080
CMD ["python3", "app.py", "--bind", "0.0.0.0:8080"]


FROM base as app
COPY ./requirements.txt /tmp/requirements.txt
RUN pip install --no-cache-dir -r /tmp/requirements.txt

COPY . /app
WORKDIR /app


FROM base as calibre_builder
RUN apt-get update && apt-get install -y --no-install-recommends \
    wget && \
    wget -nv -O- \
    https://download.calibre-ebook.com/linux-installer.sh | sh /dev/stdin install_dir=/opt && \
    apt-get remove --purge --auto-remove -y && \
    apt-get clean && \
    rm -rf \
    /tmp/* \
    /var/lib/apt/lists/* \
    /var/tmp/*


FROM calibre_builder as calibre
COPY ./requirements.txt /tmp/requirements.txt
RUN pip install --no-cache-dir -r /tmp/requirements.txt

COPY . /app
WORKDIR /app
